### ISSUE TITLE
Progress Report (8%)

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#56]
# Progress Report of *TeamSix*

https://github.com/STAT540-UBC/Repo_team_TeamSix_2021W2/blob/progress-update/reports/progress_report.md 

@kdkorthauer
@STAT540-UBC/current_tas

**Comment by kdkorthauer** [comment]
That is puzzling that they behave so differently. For both, are you including the batch as a 3-level covariate (corresponding to the three colours here)? Or only GA vs HI? If HI_t vs HI_n aren't really different batches, but you *do* expect biological variation (tumour vs normal), then you'd probably want to include that as a `group` factor in Combat/Combat_seq. And you're feeding raw counts into the function, not something normalized or transformed?

**Comment by FaezeK** [comment]
For both ComBat and ComBat_seq, we only included GA and HI as batches since as you mentioned both tumor and normal samples of Hiseq were sequenced on the same platform. The three level colouring is only used in the visualization to see that there are still differences between normal (green dots in the above graph) and tumor (red and blue dots) samples.
`batches <- data.frame(id=mt_dat$p_id, group=mt_dat$platform)
  crc_b_crrctd <- ComBat_seq(t(as.matrix(crc)), batch = batches$group)`
  
I combined hi_t and ga as tumor group and added a genotype column as `group` based on your suggestion:
`crc_b_crrctd <- ComBat_seq(t(as.matrix(crc)), batch = mt_dat$platform, group = mt_dat$genotype)`

This is the PCA plot after batch correction using above code:
<img width="649" alt="new_pca" src="https://user-images.githubusercontent.com/11761806/112518636-c6fb6480-8d56-11eb-98c5-df614f010098.png">
it seems like it's very similar to previous PCA plots

And to answer your final question, the input to all batch correction analyses we talked about was raw counts (no transformation or normalization).

**Comment by jafarzadeh91** [comment]
Hi TeamSix,

Great work so far! You delivered an extremely well-written piece of work and it answers all of the questions expected in the progress report. 
Like Keegan, the first thing I noticed was the poor performance of Combat. The input and output to Combat_seq look very similar and the effect of batch seems to persist. Did you try using other approaches for removing the batch effect? Based on my understanding, if the sample size is large enough, using a positively-constrained linear model to remove the effect of the batch variable would result in the same results as the Bayesian approach (aka Combat) but not sure if the number of samples in your study is big enough for that to hold. You can even include the first main PCs of your data in that linear model, assuming that the first PCs are usually due to the batch effect. Obviously, this approach is not as sophisticated as Combat, so maybe ask Keegan's input on it as well. There are also tons of other SVA approaches in the field that you might look at or give a try.

Another part that was a bit puzzling to me what the fact the results for DE are suspiciously good but at the same time we didn't see any significant effect in the survival analysis model. So it makes me wonder if the effect of DE is coming from the batch effect too. Did you try running the DE by excluding the hi_t to see if you can still find those significant genes? Obviously lower number of samples reduces the statistical power, but since you get 0 values, I expect the results to be still very good.

Your mark: **8/8**

**Comment by jafarzadeh91** [comment]
Perhaps Keegan might provide some inputs here. Is it possible to apply batch correction to the output of Voom? I personally saw a lot of papers/people basically start with normalized CPM data and apply any sort of batch correction + other analysis from there.

**Comment by kdkorthauer** [comment]
I'm still puzzled by the PCA plots of the ComBat_seq output. I scanned the [code](https://github.com/STAT540-UBC/Repo_team_TeamSix_2021W2/blob/master/src/batch_corr_and_low_rm.R) and the only other thing I can think to check is removing lowly expressed genes first before batch correction? Since it seems right now you do 1. batch correction, 2. remove lowly expressed, 3. plot PCs. If for some reason the correction was happening in predominantly lowly expressed genes (doesn't really make sense, but it's the only other thing I can think of), and they are then removed, this could explain the result.

Otherwise, I think the safest thing to do is include batch as a covariate in the model (as I think you are doing).

**Comment by jafarzadeh91** [comment]
I agree with Keegan. I also saw people add like 10 first PCs as covariates to the model as well (as hidden confounders), assuming they are driven by the batch effect or other factors. The number should be chosen carefully tho.

Thanks

**Comment by cmrn-rhi** [comment]
Thank you! We'll give that a try, and we're also going to try using Wilcoxon instead of `voom` since the data appears to violate the assumption that is is normally distributed and Faeze previously worked in a lab where it was often used in the differential analysis of RNA-seq data.

**Comment by FaezeK** [comment]
The PCA plot after changing the order of operations (first removing lowly expressed genes and then performing batch correction)
<img width="475" alt="Screen Shot 2021-04-01 at 8 44 35 PM" src="https://user-images.githubusercontent.com/11761806/113378228-58f10780-932b-11eb-9ff1-f1f11e8c3135.png">

Unfortunately, it doesn't really help with mixing the data points
