### ISSUE TITLE
Missing Subtypes

### ISSUE THREAD

**Issue by clmorrison** [STAT540-UBC/Repo_team_TeamSix_2021W2#67]
Here are some ideas for handling missing subtype labels that we discussed in our meeting:

1. Use the closest label instead of the predicted label
2. Create more detailed subgroups for tumors that are in-between tumor subtypes
3. drop the NAs
4. Treat NAs as a separate group entirely (so 5 subtype labels under this scheme)

And here are some comments on these approaches, in order.

1. There are concerns that this may be biologically unjustifiable. There are also some tumors with multiple closest subtype labels. However this latter issue could possibly be overcome by choosing the label whose transcriptome centroid is closer to the transcriptome of the patient, or some similar approach to break ties.
2. This will create several smaller groups which will likely lead to insufficient statistical power for an analysis to be meaningful with these subgroups. This can also introduce numerical difficulties when actually fitting models.
3. This will reduce our sample size considerably, thus weakening our analyses. This also may introduce bias into our analysis if the data is missing in a "_non-ignorable_" way (which is a specific statistical term basically meaning the missingness is associated with some of our other variables).
4. This would make our lives considerably easier, since we wouldn't need to do any complicated analysis. This might also have a (admittedly biased) benefit to our survival analysis, since we chose the cox high risk group to have the same size as the CMS4 group. If our CMS4 group is 15% instead of the 20% I used (I used closest not predicted) then the cox high risk group would be even higher risk. I can discuss more about this in the survival analysis ticket when I get the new results.

I'm a big fan of option 4, if everyone feels it is an ok approach. Even if it isn't perfect I feel like we've already got a lot of things to handle so it might be a reasonable approach.

Why not everyone start by saying their favorite approach listed (or another) and a brief reason why. It would be great if we picked one sooner rather than later since this feeds into other analyses.

**Comment by creisle** [comment]
So one thing I wanted to look at here was what an orthogonal classifier would do with our "failed" subtypes for comparison. And then simultaneously ablate genes to see if those match up with genes the DE analysis tell us are important to a given subtype.

This is pretty easy to do in python so I did an SVC (see https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)

and tested the accuracy with 5-fold cross validation.

I then did ablation of all 20k genes with 3-fold cross validation (b/c 5-fold was super slow) and looked at how the metrics changed

This analysis highlighted the following genes

![image](https://user-images.githubusercontent.com/4342641/113050689-f98fcd80-9159-11eb-8966-3b3929d5dbd2.png)

Of the 2 obvious outliers for which the model performance decreased when used I plotted their distributions here

![image](https://user-images.githubusercontent.com/4342641/113050806-1d531380-915a-11eb-8263-ea4873c0767e.png)

It is immediately obvious why FCGBP is important for classification since it has a very different distribution for CMS3, however why S100A6 is not as clear

These are the genes which when removed improved performance. 

![image](https://user-images.githubusercontent.com/4342641/113051124-7d49ba00-915a-11eb-926f-1efdf7aca04f.png)

plotting the svc vs random forest predictions too. dunno if any of this is helpful but its interesting. We can take it or leave it when it comes to the presentation

**Comment by creisle** [comment]
This is a confusion matrix of SVC vs RF classifications. Note that once the CV model evaluation was complete, the entire dataset was used to train the model and then the classifications were done agains the unknown/RF-unclassified samples. The RF subtype here is the "nearest" subtype

![image](https://user-images.githubusercontent.com/4342641/113061908-ade42080-9167-11eb-9021-d74a2c6ee65b.png)

**Comment by creisle** [comment]
One option I was thinking is we could re-classify unknown samples to a subtype where the models agree (or the SVC picked one of the list the RF gave) and see how that impacts the survival analysis?

**Comment by FaezeK** [comment]
I like that idea

**Comment by creisle** [comment]
I re-ran the ablation with 5 cross folds (since 3 wasn't super stable) with the standard scaler. The new gene ablation outliers with respect to f1 score are

```
          gene metric     value
224       AOC2     f1  0.845494
355      ATP5D     f1  0.845494
503   C10orf75     f1  0.845494
753    C6orf62     f1  0.841202
1111    CLEC4A     f1  0.841202
1222     CRHBP     f1  0.916309
1776    FAM83G     f1  0.845494
2316      HRNR     f1  0.841202
3062     MERTK     f1  0.916309
3600    PCDH12     f1  0.839056
3691   PGLYRP3     f1  0.841202
3866   PPIP5K2     f1  0.845494
4525   SLC15A1     f1  0.841202
```

**Comment by creisle** [comment]
For each of these genes I plotted their expression per-subtype along with the relative confusion matrix (their confusion matrix minus the full set confusion matrix) to see what types of calls are impacted

low-ablated (model performance decreased with removal)

![image](https://user-images.githubusercontent.com/4342641/113336340-1ef81500-92db-11eb-8630-cce166a668f5.png)

![image](https://user-images.githubusercontent.com/4342641/113336366-27e8e680-92db-11eb-8194-dd2f4a8b0115.png)

![image](https://user-images.githubusercontent.com/4342641/113336411-3afbb680-92db-11eb-9fe2-326ab10af515.png)

![image](https://user-images.githubusercontent.com/4342641/113336432-4353f180-92db-11eb-80b4-86cfefae8365.png)

![image](https://user-images.githubusercontent.com/4342641/113336463-4e0e8680-92db-11eb-93f7-fc79431d0cfe.png)

![image](https://user-images.githubusercontent.com/4342641/113336488-5797ee80-92db-11eb-946e-06d2c96a4e28.png)

![image](https://user-images.githubusercontent.com/4342641/113336612-88782380-92db-11eb-984f-d3bad1c38752.png)

![image](https://user-images.githubusercontent.com/4342641/113336681-9cbc2080-92db-11eb-880b-037c4e391d18.png)

![image](https://user-images.githubusercontent.com/4342641/113336744-b2314a80-92db-11eb-936d-b8055dd0b5a6.png)

![image](https://user-images.githubusercontent.com/4342641/113336776-bbbab280-92db-11eb-8671-c99738b8b09c.png)


![image](https://user-images.githubusercontent.com/4342641/113336801-c412ed80-92db-11eb-854b-206dcaf555e2.png)



high-ablated (model performance improved with removal)

![image](https://user-images.githubusercontent.com/4342641/113336524-6383b080-92db-11eb-8d9f-6ef22298b712.png)

![image](https://user-images.githubusercontent.com/4342641/113336853-d2f9a000-92db-11eb-908d-5a5c8fbf8dad.png)


cut offs of +/- 3 SD used to define ablation f1 score outliers
