### ISSUE TITLE
K-means clustering

### ISSUE THREAD

**Issue by clmorrison** [STAT540-UBC/Repo_team_TeamSix_2021W2#91]
![image](https://user-images.githubusercontent.com/70670918/113526490-1ae42580-956f-11eb-8ae1-a91977b47e15.png)

Hey so here is a K-means cluster of the transcriptome compared to the tumor type. The tumor labels are on top and the cluster labels are on the left. This is using the default metric which I think is Euclidean. Maybe we should try another metric e.g. correlation or something?

At first glance I don't see any particular pattern. Since we're so close to the end of the course maybe we should just report some initial results here and say we didn't have enough time?

**Comment by cmrn-rhi** [comment]
- It would be great if you could try some other metrics and post the output here so we could take a look.
- It looks like cluster 4 is CMS4... but otherwise they do seem a bit messy. Do you have any plots to visualize this so we can get a sense of the dimensions? Also would be better for throwing on a slide, even if it just ends up being a footnote.
